version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 082846230743.dkr.ecr.us-east-2.amazonaws.com
  build:
    commands:
      - echo Building image...
      - cd extraction-jobrun
      - docker build --no-cache --provenance=false --sbom=false -t career-copilot-extractor .
      - docker tag career-copilot-extractor:latest 082846230743.dkr.ecr.us-east-2.amazonaws.com/career-copilot-extractor:latest
  post_build:
    commands:
      - echo Pushing image...
      - docker push 082846230743.dkr.ecr.us-east-2.amazonaws.com/career-copilot-extractor:latest
      - aws lambda update-function-code --function-name career-copilot-extractor --image-uri 082846230743.dkr.ecr.us-east-2.amazonaws.com/career-copilot-extractor:latest --region us-east-2