version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 082846230743.dkr.ecr.us-east-2.amazonaws.com

  build:
    commands:
      - echo Building Docker image...
      - cd agent-backend
      - docker build --provenance=false --sbom=false -t career-copilot-backend .
      - docker tag career-copilot-backend:latest 082846230743.dkr.ecr.us-east-2.amazonaws.com/career-copilot-backend:latest

  post_build:
    commands:
      - echo Pushing image...
      - docker push 082846230743.dkr.ecr.us-east-2.amazonaws.com/career-copilot-backend:latest

      - echo Updating Lambda...
      - aws lambda update-function-code \
          --function-name career-copilot-backend \
          --image-uri 082846230743.dkr.ecr.us-east-2.amazonaws.com/career-copilot-backend:latest \
          --region us-east-2